spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${database.name}?useUnicode=true&allowPublicKeyRetrieval=true&autoReconnect=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}
  dynamic:
    datasource:
      master:
        url: jdbc:mysql://localhost:3306/${database.name}?useUnicode=true&allowPublicKeyRetrieval=true&autoReconnect=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
        username: ${DB_MASTER_USERNAME:${DB_USERNAME:}}
        password: ${DB_MASTER_PASSWORD:${DB_PASSWORD:}}
        filters: stat
        initialSize: 0
        minIdle: 1
        maxActive: 200
        maxWait: 10000
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 200000
        testWhileIdle: true
        testOnBorrow: true
        validationQuery: select 1
      slave:
        url: jdbc:mysql://localhost:3306/${database.name}?useUnicode=true&allowPublicKeyRetrieval=true&autoReconnect=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
        username: ${DB_SLAVE_USERNAME:${DB_USERNAME:}}
        password: ${DB_SLAVE_PASSWORD:${DB_PASSWORD:}}
  redis:
    host: localhost
    port: 6379
    password: ${REDIS_PASSWORD:}

elasticsearch:
  open: false
  clusterName: elasticsearch
  hosts: 127.0.0.1:9200
  scheme: http
  connectTimeOut: 1000
  socketTimeOut: 30000
